### ISSUE TITLE
Resize all committee member pictures to smaller sizes

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercon/jupytercon2020-website#104]

**Comment by mariobuikhuizen** [comment]
Do you mean smaller file sizes? If so this plugin might be a quick way to optimize the size of all images on the site automatically: https://github.com/bazzite/nuxt-optimized-images

**Comment by SylvainCorlay** [comment]
Yes that is what I mean. I thought of doing this manually.

**Comment by mariobuikhuizen** [comment]
I'll take a quick look at that plugin.

**Comment by SylvainCorlay** [comment]
We could get away with an imagemagick command as well.
