### ISSUE TITLE
add link to Twitter

### ISSUE THREAD

**Issue by reshamas** [jupytercon/jupytercon2020-website#145]
add link to twitter:
https://twitter.com/JupyterCon

**Comment by SylvainCorlay** [comment]
Thanks. I think we already have social links in the menu.

**Comment by reshamas** [comment]
I see it under "Menu".
but could be good idea to add to bottom footer of home page?

**Comment by SylvainCorlay** [comment]
Yes indeed!

**Comment by jtpio** [comment]
Fixed by https://github.com/jupytercon/jupytercon2020-website/pull/212
