### ISSUE TITLE
Missing info on childcare

### ISSUE THREAD

**Issue by maartenbreddels** [jupytercon/jupytercon2020-website#16]
Merged in #13, but we did not say yet who does the childcare.

**Comment by jtpio** [comment]
Content and details are still a work-in-progress.

**Comment by jasongrout** [comment]
I'll put in a PR that adds that the information will be updated soon, so it doesn't look like an unfinished site.

**Comment by jasongrout** [comment]
PR at #135. Not sure if we should leave this open until we have the final information, though.

**Comment by jtpio** [comment]
Closing as this section is not needed anymore.
