### ISSUE TITLE
Missing local phone number in CoC

### ISSUE THREAD

**Issue by martinRenou** [jupytercon/jupytercon2020-website#21]
- Local phone number
- ~~Link to the online form missing~~

**Comment by SylvainCorlay** [comment]
Added the online form link.

**Comment by jtpio** [comment]
Closing as email and online form should be enough for this online edition:

![image](https://user-images.githubusercontent.com/591645/92791126-b2eca880-f3ac-11ea-9174-71bdc6b31f87.png)
