### ISSUE TITLE
Front page buttons for talk and tutorial schedule

### ISSUE THREAD

**Issue by jasongrout** [jupytercon/jupytercon2020-website#226]
Can we put buttons/links on the front page, right under the Register button, for the talk and tutorial schedules?

What do you think about removing the covid-19 front-page button? At this point, we have a fully virtual conference and that sort of is water under the bridge. The covid statement is still accessible from the navigation menu and footer.

CC @labarba @SylvainCorlay

**Comment by labarba** [comment]
Remove the COVID-19 button 👍

I think there may be space there for two buttons for "Tutorials" and "Talks," no?

**Comment by jtpio** [comment]
Opened https://github.com/jupytercon/jupytercon2020-website/pull/227
