### ISSUE TITLE
Update DNS to GitHub pages

### ISSUE THREAD

**Issue by datapythonista** [jupytercon/jupytercon2020-website#288]
We are going to shut down our (NumFOCUS) account with Rackspace soon, where the current https://jupytercon.com website is hosted. Looks like this is a static site already served via GitHub pages at https://jupytercon.github.io/jupytercon2020-website/

We should update the DNS of jupytercon.com so it has a CNAME record for the apex to jupytercon.github.io, and set up the custom domain in this repo. Would be great to do it asap, before we shut down rackspace. Thanks!

**Comment by datapythonista** [comment]
Not sure who has access to the jupytercon.com domain, but we're planning to shut down the server where the conference website is being hosted, and it'd be good to update the DNS to use github pages before shutting down, so the conference website doesn't have any downtime.

CC: @SylvainCorlay @jasongrout

**Comment by jasongrout** [comment]
Thanks for explicitly `@mentioning` us - I missed your first message.

@SylvainCorlay has the keys to the domain, IIRC, so he would be the one to do this.
