### ISSUE TITLE
Missing content: privacy policy, terms and conditions

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercon/jupytercon2020-website#43]
I presume we should use the ones of NumFOCUS - to be checked with Leah.

In terms of design template, the simplest one should be good enough.

**Comment by maartenbreddels** [comment]
Added in #64 but has no content yet.

**Comment by SylvainCorlay** [comment]
Note: we should remove the "Terms and Conditions"

**Comment by SylvainCorlay** [comment]
This is fixed.
