### ISSUE TITLE
Missing info: need for another youtube channel - or playlist?

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercon/jupytercon2020-website#70]
We are currently linking to PyDataTV

**Comment by SylvainCorlay** [comment]
Or we consider this a good opportunity to promote that channel more, and simply create a new playlist.

**Comment by jasongrout** [comment]
Are the videos eventually going to be published to that channel? If not, then I would say we should link to the older videos.

**Comment by SylvainCorlay** [comment]
This is now fixed.
